language: generic

sudo: false
dist: trusty

script:
  - # Find out which files in data/ have been changed in the last commit
  - FILES=$(git log -p -1 data/ | grep +++ | cut -d '/' -f 2- | sed -e 's|dev/null||g')
  - # Work on these files that have been changed in the last commit
  - which python3
  - for FILE in $FILES ; do echo "$FILE" ; python3 code/worker.py $(readlink -f "$FILE") ; done

addons:
  apt:
    packages:
      - python3-requests
