language: generic

sudo: true # Otherwise there seems to be no fuse available
dist: trusty

env:
  global:
    - DISPLAY=:99

script:
  - sudo apt-get -qq -y install xmlstarlet fbcat xvfb icewm x11-utils x11-apps netpbm xdotool libgl1-mesa-dri libgl1-mesa-dev mesa-utils libosmesa6 > /dev/null # appstream # TODO: Cache me!
  - mkdir $HOME/.icewm/
  - echo "ShowTaskBar = 0" > $HOME/.icewm/preferences
  - echo "TaskBarAutoHide = 1" > $HOME/.icewm/preferences
  - echo "TaskBarShowWorkspaces = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowAllWindows = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowClock = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowMailboxStatus = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowCPUStatus = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowWindowListMenu = 0" > $HOME/.icewm/preferences
  - # xpra start :99 # Cannot get screenshots to work
  - Xvfb :99 -screen 0 800x600x24 >/dev/null 2>&1 & # Need to set bit depth, otherwise get some black screenshots
  - # until xset -q; do echo "Waiting for X server to start..."; sleep 1; done # We are not immediately using it anyway
  - # Find out which files in data/ have been changed in the last commit
  - FILES=$(git log -1 -p data/ | grep +++ | cut -d '/' -f 2- | sed -e 's|dev/null||g')
  - # Work on these files that have been changed in the last commit
  - for FILE in $FILES ; do echo "$FILE" ; bash -e code/worker.sh $(readlink -f "$FILE") ; done

after_script:
  - # xpra stop :99
  - killall Xvfb

branches:
  only:
    - gh-pages     # test the gh-pages branch (it is not tested on Travis CI by default)
    - /(.*)/       # test every other branch
